name: Code Check
on: [push]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Flake8
      run: flake8 .
    - name: Mypy
      run: |
        mypy -p 02_movies_admin
        mypy -p 03_sqlite_to_postgres
